# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: 'github.com,140.82.118.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
    sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhVhOwCOpr9F0BZJOTsSg6jzRGWOcvBhZTlybegEH+agYe6iDlzEoLMUQP3gkIaGpXsT9yNk00ogzqCvn3kH9Ehe+0DLU3aDJubX/JM+7TYIZfUxRirqjt3tA9jI1yEbomJxr6H75gI2BFLPNuPirnINYVL93FSda0ALbqNkK3XPysoKnddQSDuUNLxv4FntywcxvG1Ih4xLxnWLRLZgdsPofWW/Uq0EVVbLxHVMjDQBawemI0kizGu59uUQdOK823+RxCfordHHkPjBoCJjW5EsC0vtcCS56US/6KSdv0gajle6yIdF4+wpMTsndsGIdMp4irXaNHHxFBMNcJvUQN egor@DESKTOP-EGUSC8H'
    sshKeySecureFile: 'MIIEowIBAAKCAQEA4VYTsAjqa/RdAWSTk7EoOo80RljnLwYWU5cm3oBB/moGHuog 5cxKCzFED94JCGhqV7E/cjZNNKIM6gr595B/RIXvtAy1N2gybm1/yTPu02CGX1MU Yq6o7d7QPYyNchG6Jica+h++YCNgRSzzbj4q5yDWFS/dxUnWtAC26jZCt1z8rKCp 3XUEg7lDS8b+BZ7csHMbxtSIeMS8Z1i0S2YHbD6H1lv1KtBFVWy8R1TIw0AWsHpi NJIsxrufblEHTivNt/kcQn6K3Rx5D4waAiY1uRLAtL7XAkuelEv+iknb9IGo5Xus iHRePsKTE7J3bBiHTKeIq12jRx8RQTDXCb1EDQIDAQABAoIBABDeSrcA09uk/Vlf WBTUTDimA7nIafYBNKapSAWcAFS1RyQFTtUlB93yoC+35WE1v9A0upUoL3tjLihP DgtUS9KrXBhUYzR0nmHZ3JkJRDWaojR8magRfx/fcCNLZENHxHGat9BFlBDKVSiY htiX2spWkPAhFy7vqhzreMXrre7f6R9572ssnYMQVPMURiSqmqUSnK+2uBn9ce5Y qKIGStUSKaptdXSYMwdQUNcm62YK5dld6XJ2nuGPZp3EYVBpX3s6mFCPBCA1ELNz 3v71Vp31aLONWGwzPQUiPCoEp2ZxSv/kqCL++3HPNi9bzKKvJxNiKJnTUqCx6FKv yvK/5AECgYEA/WurxEi0JJuFFUcqao8Yz6u1ZXaGBK+Nrrt6bov1YQuRvHfRy5Z4 DHfeF7nNDNdLpBmNnp2dZCytyVimHDLLkRWzbXfXNBkjAuCLmeoUJ2EQ/H+Zu4/q HqYmPYuKx3g83mhkDq58Da6o3o65aKeN0jLkDjr2H10MoZfcRFiJ84ECgYEA46E6 QDa4stbjTGsIAU6eTHzL0Ehn/R87pkJujdOIm8QUfebh1SXX4GRSoGf48CgoAhLQ pe5oc27VXgHkKB4NsSzBsEv+PJx2pg8JjnPkQ2V33qpXToDnpUW+/nN8HCan3BBd buga1eVvLYyyTPE4RiLHVyphpboJndzhEDYdJo0CgYA/6jUDJ1cP2I2DJVTEVVzr m6H/ehoo+mHgjPY/BVuY40MZZprqHwQeGOlR0JGvyGkSdUNrmtMEXeRi4NHcUM9Y w0FivZPwVtqmsh1jb08v82JGXKRYUt64Zi1E3nnc/y1S5r89mLI+/SsoHpUSmRfC yQUNtb83f89cviFWt4HrgQKBgQChEicL5SzQr6nrGxlxA1aUPQJjgbjDreQhg4SD KxnRTvBJHqTSlJKrH5IwGyJVnbShsvqdT5PtipHEkYYGtS1vH4J2428lKHn0i1Nx z6PH5PbrQpHA5QoFMtMxbjp2GQxSdeoHXooOrOj8zEAmndH6HwX7Mewivv+rCu7e 78u0yQKBgAOw1lVoWNlZysVCIqg+1vy5pANN1Dn6gQc2v6BgFV1lhJg4QfriVwDC BhW9lZ6Zrn/0Xug6tiBhJn9IabR7cJIX4DHD68Z9wm6ufCEW6sTuUuV6onlQrykP JmR9UCcq53lKcP63+LSlI6aHZDzaLzrTn1ai7YLu2On38OLjGLaw'






